Params:
  mod_icons:
    enableStats: true


module:
  hugoVersion:
    extended: true
    min: "0.80.0"
  imports:
  - path: "github.com/FortAwesome/Font-Awesome"
    # FS-like mounting, cf. https://github.com/bep/docuapi/blob/master/config.toml
    mounts:
    - source: "svgs/"
      target: "assets/mod-icons/fa/svg/"
    - source: "metadata/"
      target: "assets/mod-icons/fa/meta/"
